# Generated by Django 4.2.21 on 2025-07-16 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManageModule', '0003_alter_class_name_id_alter_user_class_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '简单'), (2, '中等'), (3, '困难')], default=2, verbose_name='难度')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='分值')),
                ('estimated_time', models.PositiveIntegerField(default=5, help_text='预计学生完成此题需要的时间(分钟)', verbose_name='预估耗时(分钟)')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManageModule.user', verbose_name='创建人')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#666666', max_length=20, verbose_name='标签颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '题目标签',
                'verbose_name_plural': '题目标签',
            },
        ),
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类型代码')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='科目名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='科目代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=200, verbose_name='得分点描述')),
                ('point_key', models.CharField(blank=True, help_text='用于程序自动批改时识别得分点', max_length=50, verbose_name='得分点标识')),
                ('score', models.FloatField(verbose_name='分值')),
                ('matching_rule', models.JSONField(blank=True, default=dict, verbose_name='匹配规则')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_points', to='questionManageModule.problem')),
            ],
            options={
                'verbose_name': '得分点',
                'verbose_name_plural': '得分点',
                'ordering': ['problem', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProblemContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('content_data', models.JSONField(blank=True, default=dict, verbose_name='题目内容数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='questionManageModule.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='problem_attachments/%Y/%m/%d/', verbose_name='附件')),
                ('name', models.CharField(max_length=100, verbose_name='附件名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='questionManageModule.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionManageModule.problemtype', verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='problem',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionManageModule.subject', verbose_name='所属科目'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='questionManageModule.problemtag', verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='答案内容')),
                ('content_data', models.JSONField(blank=True, default=dict, verbose_name='答案数据')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionManageModule.problem')),
            ],
            options={
                'verbose_name': '题目答案',
                'verbose_name_plural': '题目答案',
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['problem_type'], name='questionMan_problem_e256f1_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['creator'], name='questionMan_creator_32f694_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty'], name='questionMan_difficu_3024b5_idx'),
        ),
    ]
