# Generated by Django 4.2.21 on 2025-07-16 02:30

from django.db import migrations
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content_data',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict, verbose_name='答案数据'),
        ),
        migrations.AlterField(
            model_name='problemcontent',
            name='content_data',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict, verbose_name='题目内容数据'),
        ),
        migrations.AlterField(
            model_name='scoringpoint',
            name='matching_rule',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=dict, verbose_name='匹配规则'),
        ),
    ]
