# Generated by Django 4.2.21 on 2025-07-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0002_alter_answer_content_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='答案数据'),
        ),
        migrations.AlterField(
            model_name='problemcontent',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='题目内容数据'),
        ),
        migrations.AlterField(
            model_name='scoringpoint',
            name='matching_rule',
            field=models.JSONField(blank=True, default=dict, verbose_name='匹配规则'),
        ),
    ]
