# Generated by Django 4.2.21 on 2025-07-21 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0003_alter_answer_content_data_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='problem',
            name='questionMan_creator_32f694_idx',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemattachment',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemcontent',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='scoringpoint',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.answer'),
        ),
        migrations.AddField(
            model_name='problem',
            name='attachment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.problemattachment'),
        ),
        migrations.AddField(
            model_name='problem',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.problemcontent', verbose_name='题目内容'),
        ),
        migrations.AddField(
            model_name='problem',
            name='scoringPoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.scoringpoint'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['subject'], name='questionMan_subject_d1bf64_idx'),
        ),
    ]
