# Generated by Django 4.2.21 on 2025-07-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0004_remove_problem_questionman_creator_32f694_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
