# Generated by Django 4.2.21 on 2025-07-23 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManageModule', '0003_alter_class_name_id_alter_user_class_in_and_more'),
        ('questionManageModule', '0005_alter_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.answer'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.problemattachment'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.problemcontent', verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManageModule.user', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='预计学生完成此题需要的时间(分钟)', null=True, verbose_name='预估耗时(分钟)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='scoringPoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.scoringpoint'),
        ),
    ]
