# Generated by Django 4.2.21 on 2025-07-23 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0006_alter_problem_answer_alter_problem_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemcontent',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='questionManageModule.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_content', to='questionManageModule.problemcontent', verbose_name='题目内容'),
        ),
    ]
