# Generated by Django 4.2.21 on 2025-09-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0007_problemcontent_problem_alter_problem_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemcontent',
            name='problem',
        ),
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='questionManageModule.problemcontent', verbose_name='题目内容'),
        ),
    ]
