# Generated by Django 4.2.21 on 2025-09-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0008_remove_problemcontent_problem_alter_problem_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='got_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='获取的分数'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(verbose_name='答案内容text(简洁：选择填空)'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='答案数据json'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='答案解析text(应该是详细些的)'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最新更新时间'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.answer', verbose_name='答案，用于评析'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.problemattachment', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='总共的分值'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionManageModule.problemtype', verbose_name='题目类型(选择……)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='scoringPoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionManageModule.scoringpoint', verbose_name='评分要则表'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='questionManageModule.problemtag', verbose_name='题目标签'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='题目标题'),
        ),
        migrations.AlterField(
            model_name='problemcontent',
            name='content',
            field=models.TextField(verbose_name='题目内容text'),
        ),
        migrations.AlterField(
            model_name='problemcontent',
            name='content_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='题目内容json'),
        ),
        migrations.AlterField(
            model_name='problemcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='problemtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最新更新时间'),
        ),
    ]
