# Generated by Django 4.2.21 on 2025-09-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0009_problem_got_points_alter_answer_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
    ]
