# Generated by Django 4.2.21 on 2025-11-25 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0010_problem_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='知识点名称')),
                ('description', models.TextField(blank=True, verbose_name='知识点描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='questionManageModule.knowledgepoint', verbose_name='父级知识点')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionManageModule.subject', verbose_name='所属科目')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='knowledge_points',
            field=models.ManyToManyField(blank=True, related_name='problems', to='questionManageModule.knowledgepoint', verbose_name='涉及知识点'),
        ),
    ]
