# Generated by Django 4.2.21 on 2025-11-27 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionManageModule', '0011_knowledgepoint_problem_knowledge_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0.0, verbose_name='掌握度评分(1-5)')),
                ('total_questions_attempted', models.PositiveIntegerField(default=0, verbose_name='练习题数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_stats', to='questionManageModule.knowledgepoint', verbose_name='知识点')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_stats', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生掌握度',
                'verbose_name_plural': '学生掌握度',
                'unique_together': {('student', 'knowledge_point')},
            },
        ),
    ]
