# Generated by Django 4.2.21 on 2025-10-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentAndClassModule', '0003_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
