# Generated by Django 4.2.21 on 2025-11-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionManageModule', '0010_problem_is_active'),
        ('assignmentAndClassModule', '0004_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questionManageModule.problem', verbose_name='关联的题目'),
        ),
        migrations.AddField(
            model_name='assignmentstatus',
            name='answer_content',
            field=models.TextField(blank=True, null=True, verbose_name='学生答案(text)'),
        ),
        migrations.AddField(
            model_name='assignmentstatus',
            name='answer_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='学生答案(json)'),
        ),
        migrations.AddField(
            model_name='assignmentstatus',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='教师/AI反馈'),
        ),
        migrations.AlterField(
            model_name='assignmentstatus',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='assignmentstatus',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
    ]
