# Generated by Django 4.2.21 on 2025-11-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmentAndClassModule', '0005_assignment_problem_assignmentstatus_answer_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentstatus',
            name='choose_answer',
            field=models.TextField(blank=True, null=True, verbose_name='提交的选择题答案'),
        ),
    ]
