# Generated by Django 4.2.21 on 2025-11-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradingModule', '0002_submission_choose_answer_and_more'),
        ('assignmentAndClassModule', '0006_assignmentstatus_choose_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentstatus',
            name='answer_content',
        ),
        migrations.RemoveField(
            model_name='assignmentstatus',
            name='answer_data',
        ),
        migrations.RemoveField(
            model_name='assignmentstatus',
            name='choose_answer',
        ),
        migrations.RemoveField(
            model_name='assignmentstatus',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assignmentstatus',
            name='score',
        ),
        migrations.RemoveField(
            model_name='assignmentstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='assignmentstatus',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gradingModule.submission'),
        ),
    ]
