# Generated by Django 4.2.21 on 2025-06-09 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_name',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='班级')),
                ('name', models.CharField(max_length=30, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(verbose_name='手机号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('class_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManageModule.class_name')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=30, verbose_name='昵称')),
                ('phone', models.BigIntegerField(verbose_name='手机号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('class_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManageModule.class_name')),
            ],
        ),
    ]
