# Generated by Django 4.2.21 on 2025-07-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManageModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=30, verbose_name='昵称')),
                ('phone', models.BigIntegerField(verbose_name='手机号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('user_attribute', models.SmallIntegerField(choices=[(1, 'student'), (2, 'teacher')], verbose_name='属性')),
                ('class_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userManageModule.class_name')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_in',
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
