# Generated by Django 4.2.21 on 2025-07-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageModule', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_attribute',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'student'), (2, 'teacher')], null=True, verbose_name='属性'),
        ),
    ]
