# Generated by Django 4.2.21 on 2025-09-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManageModule', '0006_alter_user_gender_alter_user_user_attribute'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='class_name',
            new_name='className',
        ),
    ]
