# Generated by Django 4.2.21 on 2025-09-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageModule', '0007_rename_class_name_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_attribute',
            field=models.SmallIntegerField(blank=True, choices=[(1, '学生'), (2, '老师'), (3, '管理员'), (4, '超级管理员')], null=True, verbose_name='属性'),
        ),
    ]
