# Generated by Django 4.2.21 on 2025-09-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageModule', '0009_alter_user_user_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, default=13500000000, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_attribute',
            field=models.SmallIntegerField(choices=[(0, '未定义'), (1, '学生'), (2, '老师'), (3, '管理员'), (4, '超级管理员')], default=0, verbose_name='属性'),
        ),
    ]
