# Generated by Django 4.2.21 on 2025-10-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManageModule', '0011_classname_created_at_classname_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_in',
        ),
        migrations.AddField(
            model_name='user',
            name='class_in',
            field=models.ManyToManyField(blank=True, related_name='members', to='userManageModule.classname', verbose_name='所属班级'),
        ),
    ]
