# Generated by Django 4.2.21 on 2025-09-15 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionManageModule', '0008_remove_problemcontent_problem_alter_problem_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_text', models.TextField(blank=True, null=True, verbose_name='提交的文本')),
                ('submitted_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('submitted_image', models.ImageField(blank=True, null=True, upload_to='submissions/')),
                ('status', models.CharField(choices=[('PENDING', '待批改'), ('GRADING', '批改中'), ('ACCEPTED', '已评分'), ('WRONG_ANSWER', '答案错误'), ('COMPILE_ERROR', '编译错误'), ('RUNTIME_ERROR', '运行错误')], default='PENDING', max_length=20, verbose_name='状态')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='批改反馈')),
                ('justification', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='questionManageModule.problem', verbose_name='题目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
        ),
    ]
