# Generated by Django 4.2.21 on 2025-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradingModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='choose_answer',
            field=models.TextField(blank=True, null=True, verbose_name='提交的选择题答案'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_image',
            field=models.ImageField(blank=True, default='default_submissionImage.png', null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='提交的文本'),
        ),
    ]
