# Generated by Django 4.2.21 on 2025-11-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradingModule', '0002_submission_choose_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', '待批改'), ('GRADING', '批改中'), ('SUBMITTED', '已提交'), ('GRADED', '已批改'), ('ACCEPTED', '答案正确'), ('WRONG_ANSWER', '答案错误'), ('COMPILE_ERROR', '编译错误'), ('RUNTIME_ERROR', '运行错误')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
    ]
